### ISSUE TITLE
[component] modal

### ISSUE THREAD

**Issue by moebiusmania** [bitrockteam/amber-components#12]
A classic modal, based on the `<dialog>` element proposal. Polyfill will be required.

```html
<amber-modal>
  <p>Are you sure you want to quit?</p>
  <button>no</button>
  <button>yes</button>
</amber-modal>
```

**Attributes:**
- [x] open (native) | _boolean_ | _false_

**Methods:**
- [x] close() | native close method
- [x] showModal() | native show method

**Events:**
- [x] closed | when modal is closed | void

**Comment by alessandromenini** [comment]
Proposal: we could add `<amber-modal-header>` `<amber-modal-content>` `<amber-modal-footer>` custom elements to give the correct style inside the modal.

````html
<amber-modal>
  <amber-modal-header>Are you sure you want to quit?</amber-modal-header> 
  <amber-modal-content>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</amber-modal-content>
  <amber-modal-footer>
    <amber-button>No</amber-button>
    <amber-button>Yes</amber-button>
  </amber-modal-footer>
</amber-modal>
