### ISSUE TITLE
[component] button

### ISSUE THREAD

**Issue by moebiusmania** [bitrockteam/amber-components#4]
Basically, extending the native `<button>` element.

```html
<amber-button progress priority="primary">
  Send request
</amber-button>
```

**Attributes:**
- [x] progress (add a loading overlay)  | _boolean_ | _false_ 
- [x] priority (type of button) | _string_ | _secondary_ | _primary, secondary, tertiary_
- [x] state ("colors") | _string_ | _success, error_
- [x] fitted (like "block" in Bootstrap)  | _boolean_ | _false_ 
- [x] disabled (native)  | _boolean_ | _false_ 
- [x] type (native) | _string_ | _"button"_
 
**Methods:**
none

**Events:**
none

**Comment by alessandromenini** [comment]
Progress button 1 - without validation
- State 1 _default_
- State 2 `is-loading`
- State 3 `is-resolved` (optional)
- State 4 _default_

Progress button 2 - success
- State 1 _default_
- State 2 `is-loading`
- State 3 `is-resolved` (optional) `is-success`
- State 4 _default_

Progress button 3 - success
- State 1 _default_
- State 2 `is-loading`
- State 3 `is-resolved` (optional) `is-error`
- State 4 _default_
